os: linux
dist: trusty
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y cmake cmake-data ninja-build python3-pip ack-grep cpanminus mercurial perl libperl-dev valgrind
    - sudo dpkg-divert --local --divert /usr/bin/ack --rename --add /usr/bin/ack-grep
      # For cmake-3.x - probably not needed in trusty.
      # - sudo add-apt-repository ppa:george-edison55/precise-backports -y
install:
      # - sudo easy_install3 pip
    - which python3
      # - /usr/bin/env python3 -m sys -m random2 -c 'print(sys.executable)'
    - sudo cpanm --notest Dist::Zilla IO::All Test::Differences Test::Trap Env::Path Games::Solitaire::Verify::Solution Inline::C Inline Pod::Weaver::Section::Support Test::CPAN::Changes Test::Pod::Coverage Test::Pod Test::TrailingSpace
    - wget http://web-cpan.shlomifish.org/downloads/libtap-1.12.0.tar.bz2
    - tar -xvf libtap-1.12.0.tar.bz2
    - ( mkdir B && cd B && cmake ../libtap-1.12.0 && make && sudo make install )
    - perl CI-testing/continuous-integration-testing.pl install_deps
perl:
    - "5.22"
python:
    - "3.5"
# script: "perl black-hole-solitaire/CI-testing/continuous-integration-testing.pl"
script: true
